// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArr3zk6ruIA_O7tYK3iO5YA6Wmzvc6yh8',
    appId: '1:676270746216:web:6697a45e600144fd5f29dd',
    messagingSenderId: '676270746216',
    projectId: 'nero-sehap',
    authDomain: 'nero-sehap.firebaseapp.com',
    storageBucket: 'nero-sehap.firebasestorage.app',
    measurementId: 'G-YJQV347RLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xWyeBX4RiBWQNyW7ML7ruo_0kW--eEM',
    appId: '1:676270746216:android:28aa30dea7ffd14e5f29dd',
    messagingSenderId: '676270746216',
    projectId: 'nero-sehap',
    storageBucket: 'nero-sehap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_UZwkF-LHLoYmnVqRRRfRXq5Kz2uyt38',
    appId: '1:676270746216:ios:8f8d019646d3b4505f29dd',
    messagingSenderId: '676270746216',
    projectId: 'nero-sehap',
    storageBucket: 'nero-sehap.firebasestorage.app',
    iosBundleId: 'com.example.edu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_UZwkF-LHLoYmnVqRRRfRXq5Kz2uyt38',
    appId: '1:676270746216:ios:8f8d019646d3b4505f29dd',
    messagingSenderId: '676270746216',
    projectId: 'nero-sehap',
    storageBucket: 'nero-sehap.firebasestorage.app',
    iosBundleId: 'com.example.edu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArr3zk6ruIA_O7tYK3iO5YA6Wmzvc6yh8',
    appId: '1:676270746216:web:a02cd266f1394bc75f29dd',
    messagingSenderId: '676270746216',
    projectId: 'nero-sehap',
    authDomain: 'nero-sehap.firebaseapp.com',
    storageBucket: 'nero-sehap.firebasestorage.app',
    measurementId: 'G-3FDXGY1VDK',
  );
}
