'use client';
import { useEffect, useState } from 'react';
import { Bell, CheckCheck, Megaphone } from 'lucide-react';
import { supabase } from '../../lib/supabaseClient';
import { useApp } from '../../context/AppContext';
import { FeaturePageHero } from '../../components/FeaturePageHero';
import styles from '../student-features.module.css';
type Notice={id:string;title_ar:string;title_en?:string;body_ar:string;body_en?:string;type:string;is_read:boolean;created_at:string};
export default function NotificationsPage(){const{lang,user}=useApp();const[items,setItems]=useState<Notice[]>([]);useEffect(()=>{if(!user)return;supabase.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).then(({data})=>setItems((data||[]) as Notice[]));},[user]);const markAll=async()=>{if(!user)return;await supabase.from('notifications').update({is_read:true}).eq('user_id',user.id);setItems(x=>x.map(n=>({...n,is_read:true})));};
return <main className={styles.page}><FeaturePageHero icon={Bell} eyebrow="UPDATES" title={lang==='ar'?'الإشعارات':'Notifications'} subtitle={lang==='ar'?'آخر التنبيهات والإعلانات والردود المهمة.':'Your latest important updates.'}/><div className={styles.toolbar}><button className={styles.action} onClick={markAll}><CheckCheck size={14}/>تحديد الكل كمقروء</button></div>{!user?<div className={styles.empty}>سجل الدخول لعرض الإشعارات</div>:!items.length?<div className={styles.empty}><Bell size={38}/><strong>لا توجد إشعارات جديدة</strong></div>:<section className={styles.list}>{items.map(n=><article className={styles.card} key={n.id}><div className={styles.cardTop}><div className={styles.cardIcon}><Megaphone/></div>{!n.is_read&&<span className={styles.badge}>جديد</span>}</div><h3>{lang==='ar'?n.title_ar:n.title_en||n.title_ar}</h3><p>{lang==='ar'?n.body_ar:n.body_en||n.body_ar}</p><div className={styles.meta}>{new Date(n.created_at).toLocaleDateString(lang==='ar'?'ar-EG':'en-US')}<span>{n.type}</span></div></article>)}</section>}</main>}
