'use client';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { MessageCircle, Send } from 'lucide-react';
import { supabase } from '../../../lib/supabaseClient';
import { useApp } from '../../../context/AppContext';
import { FeaturePageHero } from '../../../components/FeaturePageHero';
import styles from '../../student-features.module.css';
type Message={id:string;message_text?:string;created_at:string;user_id:string;profiles?:{name?:string}};
export default function ForumChatPage(){const{id}=useParams<{id:string}>();const{user}=useApp();const[items,setItems]=useState<Message[]>([]);const[text,setText]=useState('');const load=useCallback(async()=>{const{data}=await supabase.from('messages').select('id,message_text,created_at,user_id,profiles(name)').eq('conversation_id',id).eq('is_deleted',false).order('created_at');setItems((data||[]) as unknown as Message[]);},[id]);useEffect(()=>{const timer=setTimeout(load,0);const channel=supabase.channel(`forum-${id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},()=>load()).subscribe();return()=>{clearTimeout(timer);supabase.removeChannel(channel)};},[id,load]);const send=async()=>{if(!user||!text.trim())return;await supabase.from('messages').insert({conversation_id:id,user_id:user.id,message_text:text.trim(),message_type:'text'});setText('');await load();};return <main className={styles.page}><FeaturePageHero icon={MessageCircle} eyebrow="LIVE DISCUSSION" title="مناقشة الكورس" subtitle="تواصل مع المدرس وزملائك في مساحة آمنة مرتبطة بالكورس."/><section className={styles.list}>{items.map(m=><article className={styles.card} key={m.id}><div className={styles.cardTop}><strong>{m.profiles?.name||'طالب'}</strong><span className={styles.badge}>{new Date(m.created_at).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'})}</span></div><p>{m.message_text}</p></article>)}</section><div className={styles.toolbar}><input className={styles.search} value={text} onChange={e=>setText(e.target.value)} placeholder="اكتب رسالتك..."/><button className={styles.action} onClick={send}><Send size={14}/>إرسال</button></div></main>}
